// ===================== RED GEMS =====================
const redGems = [
  "Cleave of Rage",
  "Glacial Hammer of Shattering",
  "Ground Slam of Earthshaking",
  "Molten Strike of the Zenith",
  "Perforate of Duality",
  "Perforate of Bloodshed",
  "Shield Crush of the Chieftain",
  "Smite of Divine Judgement",
  "Holy Flame Totem of Ire",
  "Absolution of Inspiring",
  "Earthshatter of Fragility",
  "Earthshatter of Prominence",
  "Exsanguinate of Transmission",
  "Infernal Blow of Immolation",
  "Sunder of Earthbreaking",
  "Volcanic Fissure of Snaking",
  "Animate Guardian of Smiting",
  "Bladestorm of Uncertainty",
  "Boneshatter of Complex Trauma",
  "Boneshatter of Carnage",
  "Consecrated Path of Endurance",
  "Dominating Blow of Inspiring",
  "Earthquake of Amplification",
  "Ice Crash of Cadence",
  "Rage Vortex of Berserking",
  "Tectonic Slam of Cataclysm",
  "Frozen Legion of Rallying",
  "Summon Flame Golem of Hordes",
  "Summon Flame Golem of the Meteor",
  "Summon Stone Golem of Hordes",
  "Summon Stone Golem of Safeguarding"
];

// ===================== GREEN GEMS =====================
const greenGems = [
  "Animate Weapon of Ranged Arms",
  "Animate Weapon of Self Reflection",
  "Artillery Ballista of Cross Strafe",
  "Artillery Ballista of Focus Fire",
  "Barrage of Volley Fire",
  "Bear Trap of Skewers",
  "Blade Blast of Dagger Detonation",
  "Blade Blast of Unloading",
  "Blade Flurry of Incision",
  "Blade Trap of Greatswords",
  "Blade Trap of Laceration",
  "Blade Vortex of the Scythe",
  "Bladefall of Impaling",
  "Bladefall of Volleys",
  "Burning Arrow of Vigour",
  "Caustic Arrow of Poison",
  "Cremation of Exhuming",
  "Cremation of the Volcano",
  "Cyclone of Tumult",
  "Detonate Dead of Chain Reaction",
  "Detonate Dead of Scavenging",
  "Double Strike of Impaling",
  "Double Strike of Momentum",
  "Dual Strike of Ambidexterity",
  "Elemental Hit of the Spectrum",
  "Ethereal Knives of Lingering Blades",
  "Ethereal Knives of the Massacre",
  "Explosive Concoction of Destruction",
  "Explosive Trap of Magnitude",
  "Explosive Trap of Shrapnel",
  "Fire Trap of Blasting",
  "Flicker Strike of Power",
  "Frenzy of Onslaught",
  "Frost Blades of Katabasis",
  "Galvanic Arrow of Energy",
  "Galvanic Arrow of Surging",
  "Ice Shot of Penetration",
  "Ice Trap of Hollowness",
  "Lacerate of Butchering",
  "Lacerate of Haemorrhage",
  "Lancing Steel of Spraying",
  "Lightning Arrow of Electrocution",
  "Lightning Strike of Arcing",
  "Mirror Arrow of Bombarding Clones",
  "Mirror Arrow of Prismatic Clones",
  "Poisonous Concoction of Bouncing",
  "Puncture of Shanking",
  "Rain of Arrows of Artillery",
  "Rain of Arrows of Saturation",
  "Reave of Refraction",
  "Scourge Arrow of Menace",
  "Seismic Trap of Swells",
  "Shattering Steel of Ammunition",
  "Shrapnel Ballista of Steel",
  "Siege Ballista of Splintering",
  "Spectral Shield Throw of Shattering",
  "Spectral Throw of Materialising",
  "Split Arrow of Splitting",
  "Splitting Steel of Ammunition",
  "Storm Rain of the Conduit",
  "Storm Rain of the Fence",
  "Summon Ice Golem of Hordes",
  "Summon Ice Golem of Shattering",
  "Tornado of Elemental Turbulence",
  "Tornado Shot of Cloudburst",
  "Toxic Rain of Sporeburst",
  "Toxic Rain of Withering",
  "Viper Strike of the Mamba",
  "Volatile Dead of Confinement",
  "Volatile Dead of Seething",
  "Wild Strike of Extremes"
];

// ===================== BLUE GEMS =====================
const blueGems = [
  "Arc of Oscillating",
  "Arc of Surging",
  "Armageddon Brand of Recall",
  "Armageddon Brand of Volatility",
  "Ball Lightning of Orbiting",
  "Ball Lightning of Static",
  "Bane of Condemnation",
  "Blight of Atrophy",
  "Blight of Contagion",
  "Cold Snap of Power",
  "Contagion of Subsiding",
  "Contagion of Transference",
  "Crackling Lance of Branching",
  "Crackling Lance of Disintegration",
  "Discharge of Misery",
  "Divine Ire of Disintegration",
  "Divine Ire of Holy Lightning",
  "Essence Drain of Desperation",
  "Essence Drain of Wickedness",
  "Eye of Winter of Finality",
  "Eye of Winter of Transience",
  "Firestorm of Meteors",
  "Firestorm of Pelting",
  "Flame Surge of Combusting",
  "Flameblast of Celerity",
  "Flameblast of Contraction",
  "Forbidden Rite of Soul Sacrifice",
  "Frost Bomb of Forthcoming",
  "Frost Bomb of Instability",
  "Galvanic Field of Intensity",
  "Glacial Cascade of the Fissure",
  "Hexblast of Contradiction",
  "Hexblast of Havoc",
  "Ice Nova of Deep Freeze",
  "Ice Nova of Frostbolts",
  "Ice Spear of Splitting",
  "Icicle Mine of Fanning",
  "Icicle Mine of Sabotage",
  "Incinerate of Expanse",
  "Incinerate of Venting",
  "Kinetic Blast of Clustering",
  "Kinetic Bolt of Fragmentation",
  "Kinetic Rain of Impact",
  "Lightning Conduit of the Heavens",
  "Lightning Spire Trap of Overloading",
  "Lightning Spire Trap of Zapping",
  "Lightning Tendrils of Eccentricity",
  "Lightning Tendrils of Escalation",
  "Lightning Trap of Sparking",
  "Penance Brand of Conduction",
  "Penance Brand of Dissipation",
  "Power Siphon of the Archmage",
  "Purifying Flame of Revelations",
  "Pyroclast Mine of Sabotage",
  "Raise Spectre of Transience",
  "Raise Zombie of Falling",
  "Raise Zombie of Slamming",
  "Righteous Fire of Arcane Devotion",
  "Scorching Ray of Immolation",
  "Soulrend of Reaping",
  "Soulrend of the Spiral",
  "Spark of the Nova",
  "Spark of Unpredictability",
  "Storm Brand of Indecision",
  "Summon Carrion Golem of Hordes",
  "Summon Carrion Golem of Scavenging",
  "Summon Chaos Golem of Hordes",
  "Summon Chaos Golem of the Maelström",
  "Summon Holy Relic of Conviction",
  "Summon Lightning Golem of Hordes",
  "Summon Raging Spirit of Enormity",
  "Summon Reaper of Eviscerating",
  "Summon Reaper of Revenants",
  "Summon Skeletons of Archers",
  "Summon Skeletons of Mages",
  "Void Sphere of Rending",
  "Vortex of Projection"
];

// ===================== ROLL 3 UNIQUE PER COLOR =====================
function rollMultiple(list, count) {
  const result = [];
  while (result.length < count) {
    const pick = list[Math.floor(Math.random() * list.length)];
    if (!result.includes(pick)) result.push(pick);
  }
  return result;
}

function rollGems() {
  const red = rollMultiple(redGems, 3);
  const green = rollMultiple(greenGems, 3);
  const blue = rollMultiple(blueGems, 3);

  document.getElementById("redGem").innerText = "🔴 Red: " + red.join(", ");
  document.getElementById("greenGem").innerText = "🟢 Green: " + green.join(", ");
  document.getElementById("blueGem").innerText = "🔵 Blue: " + blue.join(", ");
}

